"""Word2Vec Semantic Vector Engine using Gensim."""
import os
import logging
from pathlib import Path
from typing import List, Dict, Any, Optional
import numpy as np
from app.core.config import settings, WORD2VEC_MODEL_PATH, CORPUS_FILE
from app.services.tokenizer import tokenize_words

logger = logging.getLogger(__name__)

_W2V_MODEL = None

def get_or_train_word2vec():
    """
    Retrieves cached Word2Vec model or trains a fresh domain model if missing.
    Ensures zero heavy downloads required to run out-of-the-box.
    """
    global _W2V_MODEL
    if _W2V_MODEL is not None:
        return _W2V_MODEL
        
    try:
        from gensim.models import Word2Vec
    except ImportError:
        logger.error("Gensim is not installed.")
        return None
        
    if WORD2VEC_MODEL_PATH.exists():
        try:
            _W2V_MODEL = Word2Vec.load(str(WORD2VEC_MODEL_PATH))
            logger.info("Loaded pre-trained Word2Vec model from cache.")
            return _W2V_MODEL
        except Exception as e:
            logger.warning(f"Could not load cached model ({e}), retraining...")
            
    # Train lightweight domain Word2Vec model on bundled corpus
    try:
        sentences = []
        if CORPUS_FILE.exists():
            with open(CORPUS_FILE, "r", encoding="utf-8") as f:
                for line in f:
                    if line.strip():
                        toks = tokenize_words(line)
                        if toks:
                            sentences.append(toks)
        else:
            # Fallback inline domain sentences
            sentences = [
                ["python", "machine", "learning", "data", "science", "deep", "learning"],
                ["fastapi", "flask", "django", "rest", "api", "backend", "microservices"],
                ["aws", "cloud", "docker", "kubernetes", "devops", "ci", "cd"],
                ["sql", "postgresql", "mysql", "database", "redis", "mongodb"],
                ["pytorch", "tensorflow", "scikit-learn", "nlp", "transformers", "bert"]
            ]
            
        model = Word2Vec(
            sentences=sentences,
            vector_size=settings.W2V_VECTOR_SIZE,
            window=settings.W2V_WINDOW,
            min_count=settings.W2V_MIN_COUNT,
            workers=2,
            epochs=settings.W2V_EPOCHS,
            seed=42
        )
        
        # Ensure model directory exists
        WORD2VEC_MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)
        model.save(str(WORD2VEC_MODEL_PATH))
        _W2V_MODEL = model
        logger.info(f"Trained and saved Word2Vec model with vocab size {len(model.wv)}")
        return _W2V_MODEL
    except Exception as e:
        logger.error(f"Error training Word2Vec model: {e}")
        return None

def compute_document_vector(tokens: List[str]) -> np.ndarray:
    """
    Computes document-level embedding by averaging word vectors for in-vocabulary tokens.
    Handles out-of-vocabulary (OOV) tokens safely.
    """
    model = get_or_train_word2vec()
    vec_size = settings.W2V_VECTOR_SIZE
    
    if model is None or not tokens:
        return np.zeros(vec_size)
        
    vectors = []
    for tok in tokens:
        clean_tok = tok.lower().strip()
        if clean_tok in model.wv:
            vectors.append(model.wv[clean_tok])
            
    if not vectors:
        return np.zeros(vec_size)
        
    return np.mean(vectors, axis=0)

def compute_w2v_similarity(tokens1: List[str], tokens2: List[str]) -> Dict[str, Any]:
    """
    Computes cosine similarity between two document vectors generated by Word2Vec.
    """
    vec1 = compute_document_vector(tokens1)
    vec2 = compute_document_vector(tokens2)
    
    norm1 = np.linalg.norm(vec1)
    norm2 = np.linalg.norm(vec2)
    
    if norm1 == 0.0 or norm2 == 0.0:
        return {
            "similarity": 0.0,
            "similarity_pct": 0.0,
            "in_vocab_count_1": sum(1 for t in tokens1 if _W2V_MODEL and t in _W2V_MODEL.wv),
            "in_vocab_count_2": sum(1 for t in tokens2 if _W2V_MODEL and t in _W2V_MODEL.wv)
        }
        
    cos_sim = float(np.dot(vec1, vec2) / (norm1 * norm2))
    # Normalize from [-1, 1] to [0, 1] for intuitive percentage
    bounded_sim = max(0.0, min(1.0, (cos_sim + 1.0) / 2.0))
    
    return {
        "similarity": bounded_sim,
        "similarity_pct": round(bounded_sim * 100.0, 1),
        "raw_cosine": round(cos_sim, 4)
    }

def get_word_similarities(word: str, top_n: int = 5) -> List[Dict[str, Any]]:
    """
    Returns most semantically similar terms for educational display.
    """
    model = get_or_train_word2vec()
    if model is None or word.lower() not in model.wv:
        return []
    try:
        results = model.wv.most_similar(word.lower(), topn=top_n)
        return [{"word": w, "similarity": round(float(sim), 4)} for w, sim in results]
    except Exception:
        return []
